#!/bin/bash

NAME=<APP_NAME>                                    # Name of the application
NUM_WORKERS=<NUM_WORKERS>                          # How many worker processes should Gunicorn spawn
WSGI_MODULE=<MOUNTED_WSGI_PATH>                    # WSGI module path
SOCKFILE=/wsgi_app/run/gunicorn.sock               # Communication using this unix socket

# Creates the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start Gunicorn
exec gunicorn ${WSGI_MODULE}:application \
  --name=$NAME \
  --workers=$NUM_WORKERS \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-

