version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - </PROJECT/PARENT/PATH>:/wsgi_app
      - <NGINX_CONF_DIR_PATH>:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: <BUILDDIR>
    container_name: dj01
#    command: bash -c "python /webapps/invite_user/invite/manage.py makemigrations && python /webapps/invite_user/invite/manage.py migrate && /configs/gunicorn_start"
    command: bash -c "/configs/gunicorn_start"
    volumes:
      - </PROJECT/PARENT/PATH>:/wsgi_app
    expose:
      - "8000"
      - "80"
    network_mode: "host"

