version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:80"
#      - "8000:8000"
    volumes:
      - </PROJECT/PARENT/PATH>:/wsgi_app
      - ./<NGINX_CONF_DIR>:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dj01
    command: bash -c "/configs/gunicorn_start"
    volumes:
      - </PROJECT/PARENT/PATH>:/wsgi_app
    expose:
      - "8000"
      - "80"
    network_mode: "host"

